site_name: AP Computer Science
site_url: https://dkessner.github.io/APCS

theme:
  name: material
  palette: 
    primary: deep orange
  logo: images/phyllotaxis_orange.png

extra_css:
  - style.css

nav:
  - Home: index.md
  - class/schedule.md
  - Class:
    - class/intro.md
    - class/syllabus.md
    - class/course_expectations.md
    - class/study_advice.md
    - class/resources.md
    - summer/summer_assignment.md
  - Setup:
    - setup/installation_mac.md
    - setup/github.md
    - setup/command_line.md
    - setup/customization_mac.md
  - Assignments:
    - assignments/assignment0.md
    - assignments/assignment1.md
    - assignments/assignment2.md
    - assignments/assignment3.md
    - assignments/assignment4.md
    - assignments/assignment5.md
    - assignments/assignment6.md
    - assignments/assignment7.md
    - assignments/assignment8.md
    - assignments/assignment9.md
    - assignments/assignment10.md
    - assignments/assignment11.md
  - about.md

